version: "3.8"

x-common-variables: &common-variables
  - BUGSNAG_KEY=${BUGSNAG_KEY}
  - S3_BUCKET=${S3_BUCKET}
  - LOGS_S3_BUCKET=${LOGS_S3_BUCKET}
  - MS_TEAMS_WEBHOOK_URL=${MS_TEAMS_WEBHOOK_URL}
  - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
  - GITHUB_SHA=${GITHUB_SHA}
  - GITHUB_REF_SLUG=${GITHUB_REF_SLUG}
  - TRANSITFEEDS_KEY=${TRANSITFEEDS_KEY}
  - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
  - GITHUB_WORKSPACE=${GITHUB_WORKSPACE}
  - GITHUB_RUN_ID=${GITHUB_RUN_ID}
  - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
  - AUTH0_PUBLIC_KEY=${AUTH0_PUBLIC_KEY}
  - AUTH0_CONNECTION_NAME=${AUTH0_CONNECTION_NAME}
  - AUTH0_DOMAIN=${AUTH0_DOMAIN}
  - AUTH0_API_CLIENT=${AUTH0_API_CLIENT}
  - AUTH0_API_SECRET=${AUTH0_API_SECRET}
  - OSM_VEX=${OSM_VEX}
  - SPARKPOST_KEY=${SPARKPOST_KEY}
  - SPARKPOST_EMAIL=${SPARKPOST_EMAIL}
  - GTFS_DATABASE_URL=jdbc:postgresql://postgres/dmtest
  - GTFS_DATABASE_USER=root
  - GTFS_DATABASE_PASSWORD=e2e
  - MONGO_DB_NAME=data_manager
  - MONGO_HOST=mongo:27017
  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - AWS_REGION=${AWS_REGION}
  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - DISABLE_AUTH=true

services:
  datatools-server:
    image: ghcr.io/ibi-group/datatools-server:dev
    restart: always
    environment: *common-variables
    volumes:
      - type: bind
        source: ./server/
        target: /config
    ports:
      - "4000:4000"
  datatools-ui:
    build:
      context: ../
      dockerfile: ./docker/ui/Dockerfile
      args: *common-variables
    restart: always
    environment: *common-variables
    ports:
      - "9966:9966"
  mongo:
    image: mongo
    restart: always
    volumes:
      - dt-mongo:/data/db
  postgres:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: root
      POSTGRES_PASS: e2e
      POSTGRES_DB: dmtest
    image: postgres
    restart: always
    volumes:
      - dt-postgres:/var/lib/postgresql/data
volumes:
  dt-postgres:
  dt-mongo:
