name: PR E2E Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  pr-e2e-check:
    # Run e2e tests:
    # - on pull request changed from draft to ready-for-review
    # - on commits to:
    #   * PRs to master
    #   * PRs to dev that are not draft
    #   * PRs to dev on branches created by dependabot
    if: "${{
      github.event_name == 'pull_request' && (
        github.event.action == 'review_requested' ||
        github.base_ref == 'master' ||
        (github.base_ref == 'dev' && (
          github.event.pull_request.draft == false ||
          startsWith(github.head_ref, 'dependabot/')
        ))
      )
      }}"
    uses: ./.github/workflows/node-ci.yml
    with:
      e2e: true
    secrets: inherit
