name: Commit Checks

on: [push]

jobs:
  push-checks:
    uses: ./.github/workflows/node-ci.yml
    with:
      # Run e2e tests on pushes to dev and master.
      e2e: ${{ github.ref_name == 'dev' || github.ref_name == 'master' }}
    secrets: inherit
